[package]
name = "hexalite-common"
version = "0.1.0"
edition = "2021"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
home = "^0"
lazy_static = "^1"
anyhow = "^1.0"
